### ISSUE TITLE
Need Clarification: Can an agent talk to multiple backends.

### ISSUE THREAD

**Issue by SachinHg** [google/inverting-proxy#65]
Hi @ojarjur ,
I was looking at this project and stumbled upon a doubt. In the https://github.com/google/inverting-proxy#running-backends it is mentioned that 
```
you can run the agent alongside your server with the following command...
```
This suggests that there is a 1:1 mapping between agent and backend(server). Is this assumption correct or can there be an agent talking to multiple backends? 
It would be really helpful if you could clarify this doubt.

Thanks

**Comment by ojarjur** [comment]
Hi @SachinHg, thanks for reaching out.

The agent expects a single target address for it to forward requests to. However, that does not mean you have to have a single agent per backend server. Instead, the target can be a reverse proxy that knows how to forward requests to various backends running behind it.

Essentially, the agent only tries to do one thing: provide a controlled pathway into an otherwise isolated part of your network. Any functionality beyond that should be provided by a separate proxy that is tailored to your particular needs. By composing those two proxies together, you can achieve very sophisticated network architectures without any of the individual pieces being overly complex.

My general guideline for setting this up is to run one agent per-network-isolation-boundary.

For example, if you have multiple servers running in different networks (or, that in general should not be able to communicate with each other), then each backend should get its own agent.

In contrast, if you are running multiple servers on a single VM or running them in multiple VMs that can communicate with each other, then you should probably just run a single agent with a second layer of reverse proxy.

**Comment by ojarjur** [comment]
Closing this out on the assumption that my answer above was sufficient.

@SachinHg if you have any follow up questions or something in my answer did not clarify things enough, then please feel free to reopen this issue.

**Comment by SachinHg** [comment]
Thanks for the detailed explanation @ojarjur . This was really helpful. I will reach out to you in case I have more questions regarding this.
